### ISSUE TITLE
Will not notate to studies or board analysis

### ISSUE THREAD

**Issue by conspiracy0** [ChrisAntley1/Speech-to-Text-Lichess#16]
This may be a feature request more than an issue, but it would be extremely helpful for my purposes to be able to dictate the moves in a game not played against an AI or a matched lichess player, but locally.

**Comment by ChrisAntley1** [comment]
I tried to look into this while developing the extension. Unfortunately, both input methods used (text input box and API submission) are unavailable in both studies and and analysis of games. I'd love to add this in the future if it becomes possible!

It's also possible that I haven't considered every method for controlling pieces. The only other option I know of is programmatic user input, but since it's not true mouse clicks or keystrokes, any event fired gets marked "untrusted". I know that the text input box doesn't accept these events (hence needing to press enter to submit moves through the input box), and I'd imagine the board also doesn't.
